Change postgresql.useSubChart to .enabled
PrefectHQ/prefect-helm pull request #341
Opened 2024-05-31 02:08 UTC by mitchnielsen

Changes `postgresql.useSubChart` to `postgresql.enabled`, following the common convention mentioned in https://helm.sh/docs/topics/charts/https://helm.sh/docs/topics/charts/.

This should hopefully make it clearer what that key does.

Other commits in this PR have commit messages explaining what and why.

Closes https://github.com/PrefectHQ/prefect-helm/issues/336

2024-05-31 20:25 UTC, mitchnielsen commented
Jotting down action items for myself:

Caught up with @jamiezieziula on this. The `postgresql.auth` key in `values.yaml` is Prefect-specific, so we need to allow `auth` settings to be set outside of the scope of `postgresql` when the built-in PG chart isn't used (`postgresql.enabled=false`).

We'll also want to support passing no auth and no database for those who want to test with the SQLite DB.

2024-06-04 19:56 UTC, jamiezieziula commented on charts/prefect-server/values.schema.json
> +        "enabled": {
this already exists on line 599

2024-06-04 19:57 UTC, jamiezieziula requested changes
There is a duplicate `enabled` map in the json schema. Also, can you remove all `form: true` fields in the schema, these aren't needed (we removed most before but must have missed these)

2024-06-04 20:39 UTC, mitchnielsen commented on charts/prefect-server/values.schema.json
> +        "enabled": {
Good catch, removed in 351e405.

2024-06-04 20:40 UTC, mitchnielsen commented
Removed `form` fields from the server schema in db29dcf.

2024-06-04 20:41 UTC, jamiezieziula approved these changes

2024-06-04 20:54 UTC, parkedwards approved these changes

2024-06-04 21:47 UTC, mitchnielsen commented
- Failures seem to be from hitting the Docker pull limit.
- Will proceed with merge soon but wanted to give the community member a chance to chime in.
- Will also consider if this could be a breaking change 🤔

2024-06-05 06:12 UTC, pythonking6 commented
This is excellent!!!

2024-06-05 16:06 UTC, merged