fix: Bad PrometheusRule annotations for server down
PrefectHQ/prefect-helm pull request #370
Opened 2024-08-11 10:24 UTC by TheBeege

The suggested `PrometheusRule` annotations for the server down alert were copied from the flow run crashed or failed alert. This rewrites the annotations to be more accurate. 

Let me know if you'd prefer a different wording.

2024-08-12 17:28 UTC, mitchnielsen requested changes
Thanks for catching this @TheBeege, just one small suggestion!

2024-08-12 17:28 UTC, mitchnielsen commented on charts/prometheus-prefect-exporter/values.yaml
> +  #     description: The total number of Prefect server pods in the Prefect namespace is zero
```suggestion
  #     description: There are no Prefect server pods in the "prefect" namespace
```

Just a slight rephrase for clarity, and downcases + quotes the namespace name. Feel free to tweak this as needed 👍🏼

2024-08-22 03:51 UTC, TheBeege commented
> Thanks for catching this @TheBeege, just one small suggestion!

Thanks for the suggestion! Updated

2024-08-22 20:26 UTC, mitchnielsen approved these changes

2024-08-22 20:26 UTC, mitchnielsen commented
Thanks again @TheBeege 🤝

2024-08-22 20:26 UTC, merged